=== champix56/2023-07-26-pxm/validation/dtd/cvgen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2013 sp1 (http://www.altova.com)-->
<!ELEMENT tel (#PCDATA)>
<!ELEMENT pnom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT permis EMPTY>
<!ATTLIST permis
	value CDATA #REQUIRED
>
<!ELEMENT option (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT langues ((langue+))>
<!ELEMENT langue EMPTY>
<!ATTLIST langue
	ecris  (true|false)   #REQUIRED
	langName (en|es|fr|al) #REQUIRED
	lu  (true|false)   #REQUIRED
	matern  (true|false)  #REQUIRED
	parle (true|false)  #REQUIRED
>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT ident ((nom, pnom,pnom?, pnom?, pnom?, ((mail, tel)|adresse), permis, datenaiss, age, langues))>
<!ATTLIST ident
	idciv IDREFS #REQUIRED
>
<!ELEMENT formations ((formation+))>
<!ELEMENT formation ((intitule, diplomes))>
<!ELEMENT diplomes ((diplome+))>
<!ELEMENT diplome ((intitule, option))>
<!ATTLIST diplome
	note CDATA #IMPLIED
	obtenu (true|false)  #REQUIRED
>
<!ELEMENT datenaiss (#PCDATA)>
<!ELEMENT cvs (civilites,cv+)>
<!ELEMENT civilites (civilite+)>
<!ELEMENT civilite (#PCDATA)>
<!ATTLIST civilite 
	id ID #REQUIRED
	>	
<!ELEMENT cv ((ident, formations))>
<!ATTLIST cv
	id ID #REQUIRED
>
<!ELEMENT age (#PCDATA)>

=== champix56/2023-07-26-pxm/validation/dtd/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cvs SYSTEM "cvgen.dtd">
<cvs>
<civilites>
	<civilite id="M">Monsieur</civilite>
	<civilite id="Mme">Madame</civilite>
	<civilite id="Mlle">Mademoiselle</civilite>
	<civilite id="Me">Maitre</civilite>
	<civilite id="Dr">Docteur</civilite>
	<civilite id="Pr">Professeur</civilite>
</civilites>
	<cv id="C123">
		<ident idciv="M Dr">
			<nom>DESORBAIX</nom>
			<pnom>Alexandre</pnom>
			<mail>desorbaix@free.fr</mail>
			<tel>06.64.27.63.60</tel>
			<permis value="AB"/>
			<datenaiss>1984-08-03</datenaiss>
			<age>39</age>
			<langues>
				<langue langName="fr" matern="true" lu="true" ecris="true" parle="true"/>
				<langue langName="en" lu="true" ecris="true" parle="true" matern="true"/>
				<langue langName="al" lu="true" ecris="false" parle="false" matern="true"/>
			</langues>
		</ident>
		<formations>
			<formation>
				<intitule>Fac de versailles</intitule>
				<diplomes>
					<diplome note="14" obtenu="true">
						<intitule>DAEU</intitule>
						<option>B</option>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<intitule>Ecole privé Evry</intitule>
				<diplomes>
					<diplome note="18.5" obtenu="true">
						<intitule>BEP Informatique de gestion</intitule>
						<option>dev</option>
					</diplome>
					<diplome note="18.5" obtenu="true">
						<intitule>Licence Pro Assistant chef de projet</intitule>
						<option>dev</option>
					</diplome>
					<diplome note="15.5" obtenu="false">
						<intitule>Master chef de projet</intitule>
						<option>dev</option>
					</diplome>
				</diplomes>
			</formation>
		</formations>
	</cv>
	<cv id="C132">
		<ident idciv="Mme">
			<nom>DESORBAIX</nom>
			<pnom>Alexandre</pnom>
			<pnom>Dominique</pnom>
			<pnom>Joël</pnom>
			<mail>desorbaix@free.fr</mail>
			<tel>06.64.27.63.60</tel>
			<permis value="A"/>
			<datenaiss>1985-01-25</datenaiss>
			<age>40</age>
			<langues>
				<langue langName="fr" matern="true" lu="true" ecris="true" parle="true"/>
				<langue langName="en" lu="true" ecris="true" parle="true" matern="true"/>
				<langue langName="al" lu="true" ecris="false" parle="false" matern="true"/>
			</langues>
		</ident>
		<formations>
			<formation>
				<intitule>Fac de versailles</intitule>
				<diplomes>
					<diplome note="14" obtenu="true">
						<intitule>DAEU</intitule>
						<option>B</option>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<intitule>Ecole privé Evry</intitule>
				<diplomes>
					<diplome note="18.5" obtenu="true">
						<intitule>BEP Informatique de gestion</intitule>
						<option>dev</option>
					</diplome>
					<diplome note="18.5" obtenu="true">
						<intitule>Licence Pro Assistant chef de projet</intitule>
						<option>dev</option>
					</diplome>
					<diplome note="15.5" obtenu="false">
						<intitule>Master chef de projet</intitule>
						<option>dev</option>
					</diplome>
				</diplomes>
			</formation>
		</formations>
	</cv>
</cvs>
